# Generated by Django 3.1.5 on 2021-01-29 10:49

from django.db import migrations, models


def create_posts(apps, schema_editor):
    Post = apps.get_model('posts', 'Post')
    Post.objects.create(title='Post title', text='Post text')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('text', models.CharField(max_length=256)),
            ],
        ),
        migrations.RunPython(create_posts)
    ]
