- hosts: web
  vars:
    env_path: "/home/{{ ansible_user }}/{{ web_venv_name }}"
  tasks:
    - name: Install, configure, and python venv
      block:
        - apt:
            name: [python3-pip, python3-venv]
            update_cache: yes
          become: yes
        - shell: "python3 -m venv {{ web_venv_name }}"
        - pip:
            name: wheel
            virtualenv: "{{ env_path }}"
        - pip:
            name: [django,gunicorn,psycopg2]
            virtualenv: "{{ env_path }}"
    - name: Создаем файлы сервисов, конфиг nginx и папку для статики
      block:
        - template:
            src: templates/gunicorn.service.j2
            dest: /etc/systemd/system/gunicorn.service
            owner: root
            group: root
            mode: '0640'
        - template:
            src: templates/gunicorn.socket.j2
            dest: /etc/systemd/system/gunicorn.socket
            owner: root
            group: root
            mode: '0640'
        - template:
            src: templates/default.conf.j2
            dest: /etc/nginx/conf.d/default.conf
            owner: root
            group: root
            mode: '0640'
        - file:
            path: "{{ web_static_folder }}/static"
            state: directory
            owner: "{{ ansible_user }}"
            group: nginx
        - service:
            name: nginx
            state: restarted
        - shell: "systemctl enable --now gunicorn.socket"
      become: yes
    - include_tasks: tasks/code.yml
    - uri:
        url: http://localhost:80/status/